spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3307/ecommerce_db}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:123456}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show_sql: true
    hibernate:
      ddl-auto: none
open:
  api:
    serverUrl: http://localhost:${server.port}
    title: ${API_TITLE:DUMMY-API-TITLE}
    version: v1.0.0
    serverName: server test
    description: Description of API Service

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace