spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3307/ecommerce_db}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:default_password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show_sql: true
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration/mysql
    baseline-on-migrate: true
    baseline-version: 1.0.0

open:
  api:
    serverUrl: http://localhost:${server.port}
    title: ${API_TITLE:DUMMY-API-TITLE}
    version: v1.0.0
    serverName: server test
    description: Description of API Service

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace

# Swagger (springdoc-openapi)
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true